bot:
    host: 'affinity.pw'
    port: 6697
    nickname: ['Cipher', 'Cipher_', 'Cipher__']
    password:
    channels: ['#example']
    op_pass: '' #Oper pass here
    enable_ssl: True

db:
    host: 'localhost'
    user: 'root'
    port: 3306
    password:
    db: 'gazelle'
    max_connections: 20
    idle_seconds: 7200
    autocommit: True
